### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by KockaAdmiralac** [WikiaUsers/wikia-nitro#8]
Most Fandom users probably wouldn't want to bother redownloading the latest release over and over, and Electron apparently has some Squirrel integration that can be looked into.

**Comment by LunarTwilight** [comment]
This would also allow you to have an installer too iirc

**Comment by khang-nd** [comment]
How about bundling your source code and host it with Github Pages where everyone can access without downloading?

**Comment by KockaAdmiralac** [comment]
Would that bypass CORS? That's really the only reason why Nitro is a standalone application and not a Dev script.

**Comment by LunarTwilight** [comment]
How would security and etc be ensured with github pages? (since we're having people put their password into this)

**Comment by khang-nd** [comment]
Github Pages is just a service for hosting static files, not a server, so it does not interfere with the requests. But yeah, CORS is the problem.

**Comment by KockaAdmiralac** [comment]
Uploading avatars is now natively supported on the UCP, so this is no longer needed.
